#include <ansi.h>
mapping *wheres=({
          
      (["chinese":                "豹头山",
       "weizhi" :              "/d/qujing/baotou/qiandong",]),  
      (["chinese":                "宝象国",
       "weizhi" :              "/d/qujing/baoxiang/yelu4",]),  
     (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/lin5",]),
     (["chinese":                "车迟国",
       "weizhi" :              "/d/qujing/chechi/shanlu3",]),
     (["chinese":                "毒敌山",
       "weizhi" :              "/d/qujing/dudi/shanlu2",]),
     (["chinese":                "凤仙郡",
       "weizhi" :              "/d/qujing/fengxian/jiedao8",]),
     (["chinese":                "火焰山",
       "weizhi" :              "/d/qujing/firemount/xiaomiao",]),
     (["chinese":                "积雷山",
       "weizhi" :              "/d/qujing/jilei/shan8",]),
     (["chinese":                "金兜山",
       "weizhi" :              "/d/qujing/jindou/dongnei2",]),
     (["chinese":                "金平府",
       "weizhi" :              "/d/qujing/jinping/cunlu9",]),
     (["chinese":                "祭赛国",
       "weizhi" :              "/d/qujing/jisaiguo/to-baoxiang4",]),
     (["chinese":                "毛颖山",
       "weizhi" :              "/d/qujing/maoying/shanpo10",]),  
      (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/eastriver3",]),  
      (["chinese":                "平顶山",
       "weizhi" :              "/d/qujing/pingding/shan5",]), 
      (["chinese":                "盘丝洞",
       "weizhi" :              "/d/qujing/pansi/bixi6",]), 
      (["chinese":                "通天河",
       "weizhi" :              "/d/qujing/tongtian/bing4",]), 
      (["chinese":                "麒麟山",
       "weizhi" :              "/d/qujing/qilin/shan24",]), 
      (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/dalu15",]), 
      (["chinese":                "青龙山",
       "weizhi" :              "/d/qujing/qinglong/wowang3",]), 
      (["chinese":                "天竺国",
       "weizhi" :              "/d/qujing/tianzhu/jiedao14",]), 
      (["chinese":                "无底洞",
       "weizhi" :              "/d/qujing/wudidong/dong",]), 
      (["chinese":                "乌鸡国",
       "weizhi" :              "/d/qujing/wuji/shandao2",]), 
      (["chinese":                "小西天",
       "weizhi" :              "/d/qujing/xiaoxitian/lindao7",]), 
      (["chinese":                "隐雾山",
       "weizhi" :              "/d/qujing/yinwu/xuanya7",]), 
      (["chinese":                "玉华县",
       "weizhi" :              "/d/qujing/yuhua/xiaolu11",]), 
      (["chinese":                "竹节山",
       "weizhi" :              "/d/qujing/zhujie/shanlu6",]),
      (["chinese":                "朱紫国",
       "weizhi" :              "/d/qujing/zhuzi/zhuzi3",]),
      (["chinese":                "高老庄",
       "weizhi" :              "/d/gao/xiaolin1",]),
      (["chinese":                "方寸山",
       "weizhi" :              "/d/lingtai/huoyun12",]),
      (["chinese":                "普陀山",
       "weizhi" :              "/d/nanhai/zhulin17",]),
      (["chinese":                "东海龙宫",
       "weizhi" :              "/d/sea/maze3",]),
      (["chinese":                "月宫",
       "weizhi" :              "/d/moon/rain",]),
      (["chinese":                "大雪山",
       "weizhi" :              "/d/xueshan/snowmaze3",]),
      (["chinese":                "三界山",
       "weizhi" :              "/d/sanjie/cangshidong5",]),
      (["chinese":                "蜀山",
       "weizhi" :              "/d/shushan/bamboo2",]),
      (["chinese":                "地府",
       "weizhi" :              "/d/death/new-out7",]),
      (["chinese":                "天宫",
       "weizhi" :              "/d/sky/yunloutai",]),
      (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/pavillion",]),
      (["chinese":                "长安城",
       "weizhi" :              "/d/city/minju1",]),
      (["chinese":                "古墓",
       "weizhi" :              "/d/gumu/shuidi3",]),
      (["chinese":                "开封城",
       "weizhi" :              "/d/kaifeng/donghu6",]),
 });
