#include <ansi.h>
mapping *task = ({ 
        ([      "task":                YEL"µÀµÂ¾­"NOR, 
               "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIW"Ë®ÁéÖé"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                CYN"Óã¹³"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIR"ÒøÕë"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIY"ÍÁÁéÖé"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIC"Ìêµ¶"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIB"ÌôÕ½Êé"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIR"Ç§½ðôÃ"NOR,  
                "quest_type":           "Ñ°",
        ]),
        ([      "task":                HIB"Ä«¾µ"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIW"Âé½«ÅÆ"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIR"×Ï½ð¿ø"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIW"»ð¼âÇ¹"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIW"·âÉñ°ñ"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIY"·ï»ËÇÙ"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIY"½ð·¹Åè"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "¾«ÖÂÓãÏß", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "ÎÄÊé", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "ÕÐÅÆ", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "³úÍ·", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "ÉñÇ¹", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                HIG"·çÁéÖé"NOR,  
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "±¦ÄÒ", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "ÉµÃ±", 
                "quest_type":           "Ñ°", 
        ]),
        ([      "task":                "Òø¾Æºø", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¶Ç¶µ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "½ä³ß", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "»¨È¹×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "É½Ñòºú×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÊÖ½í", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Öì±Ê", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÈËÑª", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ë®ºø", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÑÌ¶·", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "»ìÔª½ð¶·", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "½ðòÔ¼ô", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "»ðÁúïÚ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÁøÊ÷Ö¦", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "·ç¿Ú´ü", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÄîÖé", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIG"ÓñÁáçç"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¾ªÌÃÄ¾", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIM"µ±Æ±"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIR"ÏãÄÒ"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¾Æ´ü", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                MAG"°ËØÔÔÆ¹âÅÁ"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "±ù´ü", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¶¨º£Öé", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "»¢Æ¤Ã±", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÈËÆ¤ÕË±¾", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Â¿°°", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ä¾ÌÒ½£", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "´ó¸«", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Í­ïµ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "·çÀ×ïµ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "µ¯Öé", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ä¾µÑ×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ðå»¨Õë", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "·ïÎ²¼ýôá", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÀÃÓãÍø", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "µØÆõ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ò»ÖùÏã", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÂÖ»Ø°ô", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ß¦ÃæÕÈ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIW"»¨²è"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIC"¿¼Ìâ"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIM"ÃÉº¹Ò©"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIR"Çë¼í"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÇÙÏÒ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIY"É××Ó"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIG"ËãÅÌ"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÆÆÑ¥×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIR"ëÙÖ¬"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIR"»ðÁéÖé"NOR,  
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÀÏ¹Å¶­", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                CYN"Ê¥ÁéÖé"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ë÷ÃüÉþ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ìú¼×ÅÛ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "°×Ê×Ì«Ðþ¾­", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "°µÉ±±¦Â¼", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÄÏ¹Ï", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIW"Î¶ÏÉÈÏÖ¤"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "µÎÌìËè", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÏóÑÀ÷»×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIB"ÌìÍ¯ËÂ´È±¯µ¶µ¶Æ×"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÂôÉíÆõ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                RED"Ñ¹Ëêºì°ü"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÕÕÑý¾µ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "°×Óñ×àóË", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¼¦Ã«ë¦×Ó", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÎÚ¼¦¹ú×åÆ×", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIM"¼ÙÑÀ¹¿"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIG"´óÌÆÓñçô"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¡¼°Ù¼ÒÐÕ¡½", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Öñô¤»þ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ñ°É½ÑüÅÆ", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "¿³ÁÖµ¶", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                YEL"´óºÅÌú´¸"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                HIB"À×ÁéÖé"NOR, 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "Ò©·½", 
                "quest_type":           "Ñ°",  
        ]),
        ([      "task":                "ÖñÀº", 
                "quest_type":           "Ñ°",  
        ]),
});

mapping query_task() 
{
        return task[random(sizeof(task))]; 
}
